# Generated by Django 5.1.6 on 2025-05-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.CharField(default='manan', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
